export const ACTION_TYPE_CHANGE_USER_MESSAGE="ACTION_TYPE_CHANGE_USER_MESSAGE";
export const ACTION_TYPE_ADD_CONTACTS = "ACTION_TYPE_ADD_CONTACTS";
export const ACTION_TYPE_DELETE_CONTACTS="ACTION_TYPE_DELETE_CONTACTS";
export const ACTION_TYPE_CHANGE_TEMPLATE = "ACTION_TYPE_CHANGE_TEMPLATE";

